kind: Namespace
apiVersion: v1
metadata:
  name: hello-universe

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-universe
  namespace: hello-universe
data:
  ADD_FUN: "yes"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hello-universe
  name: hello-universe
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-universe
  strategy:
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "50%"
    type: RollingUpdate
  template:
    spec:
      containers:
        - startupProbe:
            httpGet:
              path: "/"
              port: 5000
            timeoutSeconds: 1
            periodSeconds: 2
            failureThreshold: 2
          livenessProbe:
            tcpSocket:
              port: 5000
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/"
              port: 5000
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 2
            failureThreshold: 2
          name: hello-universe
          imagePullPolicy: IfNotPresent
          image: nanda/hello-universe:v8
          envFrom:
            - configMapRef:
                name: hello-universe
          ports:
            - protocol: TCP
              name: pythonport
              containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
      nodeSelector:
        kubernetes.io/hostname: minikube
    metadata:
      labels:
        name: hello-universe
        version: v1

---
kind: Service
apiVersion: v1
metadata:
  name: hello-universe
  namespace: hello-universe
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80
  selector:
    name: hello-universe
