kind: Namespace
apiVersion: v1
metadata:
  name: hello-universe

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: hello-universe
  name: hello-universe
spec:
  template:
    spec:
      containers:
        - livenessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 5000
            periodSeconds: 5
          name: hello-universe
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: "/"
              port: 5000
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            initialDelaySeconds: 5
            failureThreshold: 2
          image: nanda/hello-universe:v8
          ports:
            - protocol: TCP
              name: pythonport
              containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
      nodeSelector:
        kubernetes.io/hostname: minikube
    metadata:
      labels:
        name: hello-universe
        version: v1
  selector:
    matchLabels:
      name: hello-universe

---
kind: Service
apiVersion: v1
metadata:
  name: hello-universe
  namespace: hello-universe
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80
  selector:
    name: hello-universe
