{{- $root := . -}}
{{- $namespace := .Values.namespace }}
{{- $configMaps := .Values.configMaps }}
{{- range $index, $configMap := $configMaps }}
{{- $configMapData := dict "root" $root "namespace" $namespace "configMap" $configMap }}
{{- include "app.configmap" $configMapData }}
---
{{- end }}
{{- $infraConfigsData := dict "namespace" $namespace "requiredInfraConfigs" .Values.requiredInfraConfigs "allInfraConfigs" .Values.infraConfig }}
{{ include "app.infra-configmap" $infraConfigsData }}
