{{- $root := . -}}
{{- $environment := .Values.environment -}}
{{- $infraSettings := $root.Values.infraSettings -}}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      {{- toYaml .Values.rollingUpdate | nindent 6 }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.podLabels | nindent 8 }}
      {{- include "app.podAnnotations" . | indent 6 }}
    spec:
      {{- if and (eq .Values.environment "prod") (.Values.affinity) }}
      {{- include "app.affinity" .Values.affinity | trim | nindent 6 }}
      {{- end }}
      containers:
      {{- range .Values.containers }}
        - livenessProbe:
            tcpSocket:
              port: {{ .port }}
            periodSeconds: 5
          name: {{ .name }}
          envFrom:
            - configMapRef:
                name: {{ .configMapName }}
            - secretRef:
                name: {{ $root.Values.requiredInfraDependencies.name }}
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /
              port: {{ .port }}
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          image: {{ .imageName }}:{{- .imageTag }}
          ports:
            - protocol: TCP
              name: {{ .portName }}
              containerPort: {{ .port }}
          resources:
          {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            {{- include "app.containerVolumeMounts" $root.Values.configMaps | trim | nindent 12 }}
            {{- include "app.containerVolumeMounts" $root.Values.secrets | trim | nindent 12 }}
      {{ $podConfigMapVolumesData := dict "configMaps" $root.Values.configMaps "type" "configMaps" -}}
      {{ $podSecretVolumesData := dict "secrets" $root.Values.secrets "type" "secrets" -}}
      volumes:
        {{- include "app.podVolumes" $podConfigMapVolumesData | trim | nindent 8 }}
        {{- include "app.podVolumes" $podSecretVolumesData | trim | nindent 8 }}
      {{- end }}
