{{- $root := . -}}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.requiredInfraDependencies.name }}
  namespace: {{ .Values.namespace }}
data:
  # Iterate on all required keys of .requiredInfraDependencies and
  # for each key, pull the value expression and
  # lookup that expression in .infraSettings values
  {{ range $settingKey, $settingValue := .Values.requiredInfraDependencies.values }}
  {{- $settingValue := trimPrefix "$" $settingValue }}
  {{- $actualSettingValue := pluck $settingValue $root.Values.infraSettings | first }}
  {{- $settingKey -}}: {{$actualSettingValue | quote}}
  {{ end }}
---
