{{- $root := . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.requiredInfraConfigs.name }}
  namespace: {{ .Values.namespace }}
data:
  # Iterate on all required keys of .requiredInfraConfigs and
  # for each key, pull the value expression and
  # lookup that expression in .infraConfig values
  {{ range $configKey, $configValue := .Values.requiredInfraConfigs.values }}
  {{- $configValue := trimPrefix "$" $configValue }}
  {{- $actualConfigValue := pluck $configValue $root.Values.infraConfig | first }}
  {{- $configKey -}}: {{$actualConfigValue | quote}}
  {{ end }}
---
