apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    {{- range .Values.containers }}
    - protocol: TCP
      targetPort: {{ .port }}
      port: {{ .internalServicePort }}
    {{- end }}
  selector:
    name: {{ .Values.name }}
