apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    {{- range .Values.containers }}
    - nodePort: {{ .externalNodePort }}
      port: {{ .internalServicePort }}
      protocol: TCP
      targetPort: {{ .containerPort }}
    {{- end }}
  selector:
    app: {{ .Values.name }}
