# This file is usually git-ignored. Its just here for reference.
infraSettings:
  DATABASE_HOST: cHJvZC1kYi5leGFtcGxlLmNvbQ==
  DATABASE_PORT: MzMwNg==
  SERVICE_A: cHJvZC5leGFtcGxlLmNvbS9zZXJ2aWNlX2E=
