environment: local
namespace: hello-universe
name: hello-universe
podLabels:
  app: hello-universe
replicas: 1
containers:
- name: hello-universe
  port: 5000
  portName: pythonport
  internalServicePort: 80
  imageName: nanda/hello-universe
  imageTag: v12
  configMapName: config-plain
  secretName: secrets-plain
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi
# - name: nginx
#   port: 80
#   portName: httpport
#   internalServicePort: 80
#   imageName: nginx
#   imageTag: v1.18.0
#   configMapName: nginx
#   resources:
#     requests:
#       cpu: 100m
#       memory: 100M
#     limits:
#       cpu: 200m
#       memory: 200M
configMaps:
- name: config-plain
  data:
    ADD_FUN: "yes"
# - name: nginx
#   data:
    # ADD_FUN: "yeah"
- name: config-file
  file: config.json
  mountPath: /service/config.json
# NOTE: secrets are part of values-secrets.yaml
requiredInfraDependencies:
  name: app-infra
  values:
    # NOTE: All the below values are interpreted from values-infra-secrets-<env>.yaml
    MYSQL_HOST: $DATABASE_HOST
    MYSQL_PORT: $DATABASE_PORT
    SERVICE_A: $SERVICE_A
# affinity:
#   nodeAffinityLabels:
#     - name: kubernetes.io/hostname
#       value: minikube
#   podAntiAffinity:
#     type: "required" # vs preferred
#     labels: # similar to podLabels mentioned above
#       - name: app
#         value: hello-universe
rollingUpdate:
  maxSurge: "30%"
  maxUnavailable: "20%"
