name: Validate Helm Templates
on:
  push:
    branches:
      - master
jobs:
  build:
    name: helm-validate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://nanda/helm-template-validator:v0.1.0
        continue-on-error: false
      - name: Print current dir
        run: ls -alh
      - name: Run helm version
        run: helm version
