name: Validate Helm Templates
on:
  push:
    branches:
      - master
jobs:
  build:
    name: helm-validate
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        continue-on-error: false
